### ISSUE TITLE
Setup CI tests

### ISSUE THREAD

**Issue by khatchad** [mdarefin/Convert-For-Each-Loop-to-Lambda-Expression-Eclipse-Plugin#1]
Set up continuous integration tests on Travis CI.

**Comment by khatchad** [comment]
Please add tests for your precondition checking. See https://github.com/khatchad/Java-8-Interface-Refactoring/tree/master/edu.cuny.citytech.defaultrefactoring.tests.

**Comment by mdarefin** [comment]
got it, I will add all the test case, mentioning issue as well

**Comment by khatchad** [comment]
Do you have any questions here? The main things to look at are [MigrateSkeletalImplementationToInterfaceRefactoringTest.java](https://github.com/khatchad/Java-8-Interface-Refactoring/blob/master/edu.cuny.citytech.defaultrefactoring.tests/test%20cases/edu/cuny/citytech/defaultrefactoring/ui/tests/MigrateSkeletalImplementationToInterfaceRefactoringTest.java) and [resources/MigrateSkeletalImplementationToInterface](https://github.com/khatchad/Java-8-Interface-Refactoring/tree/master/edu.cuny.citytech.defaultrefactoring.tests/resources/MigrateSkeletalImplementationToInterface).

**Comment by mdarefin** [comment]
so, Far I Understand The Concept, I might need help to organize  when upload the test case

**Comment by khatchad** [comment]
It's very easy. You just put them in the `resources` directory. The name of the directory holding the test files must match the method name that does the test.

**Comment by khatchad** [comment]
You can run the test in Eclipse by selecting "run JUnit Plug-in test" or something to that effect.

**Comment by khatchad** [comment]
Alternatively, you can use `mvn install`.

**Comment by mdarefin** [comment]
install mvn is keep giving me error, I am not sure if it's mac thing, google search doesn't help much. I am working on the test case

**Comment by khatchad** [comment]
That's weird. Do you still have those errors in Eclipse?

**Comment by khatchad** [comment]
Yes, please work on the test cases. We will need them! In fact, I wonder if NetBeans has any.

**Comment by mdarefin** [comment]
Yeah, I still have the error in pom.xml file, I will search if NetBean  has any testcase

**Comment by khatchad** [comment]
Hm. This is after you pulled? That's strange because I don't see the error on my machine anymore.

**Comment by khatchad** [comment]
Moving discussion to https://github.com/mdarefin/Convert-For-Each-Loop-to-Lambda-Expression-Eclipse-Plugin/issues/14.

**Comment by mdarefin** [comment]
I did the pull in my laptop and desktop

**Comment by khatchad** [comment]
I think these tests are quite important
you should get to this issue if you can so that way you can know for sure that your implementation is correct

**Comment by khatchad** [comment]
It is a JUnit test
See how it extends RefactoringTest?
The methods that start with the word "test" are the ones that JUnit runs

**Comment by khatchad** [comment]
like testMethodWithStatements

**Comment by khatchad** [comment]
Then in https://github.com/khatchad/Java-8-Interface-Refactoring/tree/master/edu.cuny.citytech.defaultrefactoring.tests/resources/MigrateSkeletalImplementationToInterface
You'll see a bunch of directories
Notice how each directory corresponds to a test\* method name?

**Comment by khatchad** [comment]
The ones that only have a subdirectory named "in" are for failed preconditions
"out" is for passing
You could start with the failed ones
https://github.com/khatchad/Java-8-Interface-Refactoring/tree/master/edu.cuny.citytech.defaultrefactoring.tests/resources/MigrateSkeletalImplementationToInterface/testMethodWithStatements/in
that's the directory that corresponds to the test case I mentioned earlier
Then, inside that directory, there's a class named A that has a method m(). m() fails the precondition. In your case, you'd have one enhanced for loop in m().
anyway, you will need to do that eventually
ideally, you'd write tests as you finish each of these preconditions
but that's ideal ☺

**Comment by khatchad** [comment]
You already have a test project. https://github.com/mdarefin/Convert-For-Each-Loop-to-Lambda-Expression-Eclipse-Plugin/tree/master/edu.cuny.citytech.foreachlooptolambda.ui.tests

**Comment by khatchad** [comment]
I believe that the best approach to take here is as follows:
1. Fork [Common-Eclipse-Refactoring-Framework](https://github.com/khatchad/Common-Eclipse-Refactoring-Framework).
2. In that repository, create a new plugin called `edu.cuny.citytech.refactoring.common.tests`. 
3. In that plugin, create a new class called `edu.cuny.citytech.refactoring.common.test.RefactoringTest.java` that extends `org.eclipse.jdt.ui.tests.refactoring.RefactoringTest`.
4. Fork [Java-8-Interface-Refactoring](https://github.com/khatchad/Java-8-Interface-Refactoring).
5. Move common methods from [`MigrateSkeletalImplementationToInterfaceRefactoringTest.java`](https://github.com/khatchad/Java-8-Interface-Refactoring/blob/master/edu.cuny.citytech.defaultrefactoring.tests/test%20cases/edu/cuny/citytech/defaultrefactoring/ui/tests/MigrateSkeletalImplementationToInterfaceRefactoringTest.java) to  `edu.cuny.citytech.refactoring.common.test.RefactoringTest.java`. Make these methods `protected` instead of `private.
6. Alter [`MigrateSkeletalImplementationToInterfaceRefactoringTest.java`](https://github.com/khatchad/Java-8-Interface-Refactoring/blob/master/edu.cuny.citytech.defaultrefactoring.tests/test%20cases/edu/cuny/citytech/defaultrefactoring/ui/tests/MigrateSkeletalImplementationToInterfaceRefactoringTest.java) and [`ForeachLoopToLambdaRefactoringTest.java`](https://github.com/mdarefin/Convert-For-Each-Loop-to-Lambda-Expression-Eclipse-Plugin/blob/master/edu.cuny.citytech.foreachlooptolambda.ui.tests/test%20cases/edu/cuny/citytech/foreachlooptolambda/tests/ForeachLoopToLambdaRefactoringTest.java) to extend `edu.cuny.citytech.refactoring.common.test.RefactoringTest.java` instead of `org.eclipse.jdt.ui.tests.refactoring.RefactoringTest`.

Once that's done, I think it will be extremely easy for you to add test cases to [`ForeachLoopToLambdaRefactoringTest.java`](https://github.com/mdarefin/Convert-For-Each-Loop-to-Lambda-Expression-Eclipse-Plugin/blob/master/edu.cuny.citytech.foreachlooptolambda.ui.tests/test%20cases/edu/cuny/citytech/foreachlooptolambda/tests/ForeachLoopToLambdaRefactoringTest.java). We can go from there.

**Comment by mdarefin** [comment]
Thank you for the steps. Start working on this ASAP

**Comment by mdarefin** [comment]
I am getting bunch off error, configure build path. would need assistance

**Comment by khatchad** [comment]
You are probably just missing some dependencies. Try using a quick fix or just copy the dependencies from the manifest files of the other plugin.

**Comment by mdarefin** [comment]
Ok, thank you.

**Comment by mdarefin** [comment]
I fix the bugs, now what to do, I am getting build error in Travis, got stuck there how to fix

**Comment by khatchad** [comment]
Is there a particular commit you fixed this issue in?

**Comment by mdarefin** [comment]
I am not getitng any error in local machine, but when I did quick-fix I think it changes the manifest file. 
https://github.com/mdarefin/Convert-For-Each-Loop-to-Lambda-Expression-Eclipse-Plugin/commit/f67dc3cf70361cddd8c748df7e89daa58016e280

**Comment by mdarefin** [comment]
ok, I have move the common methods to edu.cuny/citytech.refactoring.common.test/RefactoringTest this class extend org.eclipse.jdt.ui.tests.refactoring.RefactoringTest and the ForeachLoopToLambdaRefactoringTest extend RefactoringTest, now I need to understand how the helperFail and helperPass method works in-order to put the testCase

**Comment by mdarefin** [comment]
following the instruction and setup Ci test case
https://github.com/mdarefin/Convert-For-Each-Loop-to-Lambda-Expression-Eclipse-Plugin/commit/ac30627271bcdbd910ae29342fdb251a61418c72

**Comment by khatchad** [comment]
> ... now I need to understand how the helperFail and helperPass method works in-order to put the testCase

I would not worry about this yet. I would just keep your single test method for now (the one that simply asserts true). Once everything is working, then you can add real test cases. That would be my advice.

**Comment by khatchad** [comment]
The verification first step is to get this working correctly on your local machine. To verify this, right-click your test class in Eclipse and select an option that says something like "Run JUnit Eclipse Plugin Test." Do you see that option?

**Comment by mdarefin** [comment]
I have to check when I go home, I will be home by 4pm. I will let you then.
