### ISSUE TITLE
Precondition - Check if the loop has more than one return statement and whether the return value is boolean

### ISSUE THREAD

**Issue by mdarefin** [mdarefin/Convert-For-Each-Loop-to-Lambda-Expression-Eclipse-Plugin#12]
The body of the initial for loop does not contain more than one return statement. LambdaFicator can deal with loops with only one return statement as long as they return a boolean literal and LambdaFactor can infer that they can be refactored to an anyMatch or noneMatch operation.

**Comment by khatchad** [comment]
This one has a bug. Please test. Also, I believe you should also be checking that the returned value is boolean, correct?

**Comment by mdarefin** [comment]
I did a test case 
public boolean returnStatementTestcase (boolean returnCheck) {
        List<Integer> list = Arrays.asList(2,3,4,5,6,7);
        int count =0;
        for (Integer integer : list) {
            System.out.println(integer);
            count++;
            if(count > 4)
            return returnCheck = true;
            else
                return returnCheck = false;
        }
        return returnCheck;
    }

**Comment by mdarefin** [comment]
and it  checking was working, i will do some more test and check

**Comment by khatchad** [comment]
Test with only one return statements. You're current implementation will fail when it should pass.

**Comment by mdarefin** [comment]
I did, it actually pass. I think I need to work on it,

**Comment by mdarefin** [comment]
I check with multiple test case, looks like this precondtion working, you may check and suggest any optimizations

**Comment by mdarefin** [comment]
Can you check the returnStatement I check with multiple test case, my end is working, if you see the code is good, we could close this one

**Comment by khatchad** [comment]
Can you set up some unit tests for it? See https://github.com/mdarefin/Convert-For-Each-Loop-to-Lambda-Expression-Eclipse-Plugin/issues/1.

**Comment by khatchad** [comment]
You should have a few test cases:
1. No return statement in for loop body (should pass).
2. One return statement in for loop body returning a boolean value (should pass).
3. One return statement in for loop body returning a non-boolean value (should fail).
4. Multiple return statements in for loop body, each returning a boolean values (should fail).
5. Multiple return statements in for loop body, each returning a non-boolean values (should fail).

**Comment by mdarefin** [comment]
got it, thanks. I thought the return type could be anything, not particularly boolean. I will work on it today

**Comment by mdarefin** [comment]
HOw to check if the return types is boolean

**Comment by khatchad** [comment]
From the issue statement:

> LambdaFicator can deal with loops with only one return statement as long as they return a **boolean literal**

Though, I'm not sure why it has to be a literal (meaning explicitly a `true` or `false` keyword). Do you know? How do they check for a boolean value in NetBeans?

**Comment by mdarefin** [comment]
I couldn't find particular method. I will check again

**Comment by khatchad** [comment]
I remember seeing it.

**Comment by khatchad** [comment]
http://grepcode.com/file/bits.netbeans.org/maven2/org.netbeans.modules/org-netbeans-modules-java-hints/RELEASE80-BETA/org/netbeans/modules/java/hints/jdk/mapreduce/PreconditionsChecker.java#327:

``` java
@Override
public Tree visitReturn(ReturnTree that, Trees trees) {
    ExpressionTree thatExpression = that.getExpression();
    if (!this.hasMatcherReturn && thatExpression != null && thatExpression.getKind() == Tree.Kind.BOOLEAN_LITERAL
            && thisIsMatcherReturn(that, this.getCurrentPath())) {
        this.hasMatcherReturn = true;
    } else {
        this.hasReturns = true;
    }
    return super.visitReturn(that, trees);
}
```

**Comment by khatchad** [comment]
Have a look at: http://help.eclipse.org/mars/index.jsp?topic=%2Forg.eclipse.jdt.doc.isv%2Freference%2Fapi%2Forg%2Feclipse%2Fjdt%2Fcore%2Fdom%2FReturnStatement.html

That method will give you the "that" expression. Make sure it's not `null`. Then, you basically need to check if the `Expression` is a `BooleanLiteral`. You can do that using the `getNodeType()` method, and you'll want to check for the `BOOLEAN_LITERAL` constant. Alternatively, you could also use the `instanceof` operator.

**Comment by mdarefin** [comment]
thanks for the explanation

**Comment by mdarefin** [comment]
``` java
@Override
public boolean visit(ReturnStatement node) {
    ASTNode expression = node.getExpression();
    returnCount++;
    if(returnCount > 1 && expression != null && expression.equals(ASTnode.BOOLEAN_LITERAL))
        this.encounteredReturnStatement = true;

    return super.visit(node);
}
```

**Comment by mdarefin** [comment]
can you check the method, looks like it should work, but it's faling the test case, multiple return, boolean return

**Comment by khatchad** [comment]
Can you either commit that code or place it in a [Gist](https://gist.github.com/)? It will be easier for me to comment on. Thanks.

**Comment by mdarefin** [comment]
Ok will commit.

**Comment by khatchad** [comment]
I'm still looking at https://github.com/mdarefin/Convert-For-Each-Loop-to-Lambda-Expression-Eclipse-Plugin/blob/master/edu.cuny.citytech.foreachlooptolambda.ui/src/edu/cuny/citytech/foreachlooptolambda/ui/refactorings/ForeachLoopToLambdaRefactoring.java#L141
Because I feel that there are problems here
I think you are trying to check two different things with one method and that is causing confusion

**Comment by khatchad** [comment]
in fact, I think there there are really two different preconditions here

**Comment by khatchad** [comment]
Break it into two

**Comment by khatchad** [comment]
your visitor should have two methods
containsMultipleReturns()
and containsInvalidReturn()
Call them both from https://github.com/mdarefin/Convert-For-Each-Loop-to-Lambda-Expression-Eclipse-Plugin/blob/master/edu.cuny.citytech.foreachlooptolambda.ui/src/edu/cuny/citytech/foreachlooptolambda/ui/refactorings/ForeachLoopToLambdaRefactoring.java#L141

**Comment by khatchad** [comment]
Basically, break it down into two preconditions instead of one

**Comment by khatchad** [comment]
containsMultipleReturn() simply counts the number of return statements in the for loop body

**Comment by khatchad** [comment]
the other field records whether a return statement was found that was invalid, meaning that it returned something other than a boolean literal.

**Comment by khatchad** [comment]
So in https://github.com/mdarefin/Convert-For-Each-Loop-to-Lambda-Expression-Eclipse-Plugin/blob/master/edu.cuny.citytech.foreachlooptolambda.ui/src/edu/cuny/citytech/foreachlooptolambda/ui/visitors/EnhancedForStatementVisitor.java#L11, you will have a field `private boolean encounteredInvalidReturnStatement;`.

**Comment by khatchad** [comment]
In containsMultipleReturns(), just `return returnCount > 1`.

**Comment by khatchad** [comment]
In visit(ReturnStatement node), the very first thing you do is returnCount++

**Comment by khatchad** [comment]
Moving to https://gist.github.com/khatchad/0dd6798aa0619e1bf5b4.

**Comment by mdarefin** [comment]
in the if logic wouldn't be or rather then and, now havign issue with all return type, if there is any return type in the loop, it's showing the error message
https://github.com/mdarefin/Convert-For-Each-Loop-to-Lambda-Expression-Eclipse-Plugin/commit/9d4c2f79727cf676470b877119637c93a4ec347f

**Comment by mdarefin** [comment]
in the ASTNode class  

public static final int BOOLEAN_LITERAL = 9;

I was thinking fo rboolean would bot be 0 or 1

**Comment by khatchad** [comment]
No `BOOLEAN_LITERAL` is just a constant. It can have an arbitrary value. Besides, Java doesn't use numbers for boolean types.

**Comment by khatchad** [comment]
Basically, we have another case for invalid return statements. Specifically, if you use a return statement, you must return a boolean literal. So, this should be:

``` java
if (expression == null || expression.getNodeType() != ASTNode.BOOLEAN_LITERAL) {
    this.encounteredInvalidReturnStatement = true;
```

Thus, either if the expression is null, or if the expression is not null and it is anything other than a boolean literal, we have an invalid return statement. Make sense? I'll update the #12 as well.

**Comment by mdarefin** [comment]
ok, the prolem I am facing  with the logic if (expression == null || expression.getNodeType() != ASTNode.BOOLEAN_LITERAL) is : if there is any return type it's giving me an error message.

**Comment by khatchad** [comment]
Are we good here now?

**Comment by mdarefin** [comment]
Yeah, this one is good, pass the test case
