### ISSUE TITLE
Embedded for?

### ISSUE THREAD

**Issue by khatchad** [mdarefin/Convert-For-Each-Loop-to-Lambda-Expression-Eclipse-Plugin#15]
What happens if we have multiple, embedded for loops? For example:

``` java
for (...)
    for (...)
```

Perhaps we should have a precondition that disallows any for loops contained in the original loop body? We can then relax this as appropriate.

You may also want to check what NetBeans does in this situation.

**Comment by mdarefin** [comment]
it's very good idea, I haven't see anything like inner loop in preconditions in netbeans.

**Comment by mdarefin** [comment]
inside the Enhanced for loop there could be another for-loop or enhanced for loop or while, how should we approach this problem. let's see sould we create to visit that check for-loop and enhanced for loop or should we check from.

**Comment by mdarefin** [comment]
is there any way to check with getSource() or some kind of method that will check if there is any loop inside the Enhaced for loop body

**Comment by mdarefin** [comment]
as far understand need to check any iterable class in enhanced forLoop body. is ther any method is like if the body is Iterable it fails

**Comment by mdarefin** [comment]
node.getBody() will give the body node of the enhanced for loop, how could I check if the body contains another loop,

**Comment by mdarefin** [comment]
https://github.com/mdarefin/Convert-For-Each-Loop-to-Lambda-Expression-Eclipse-Plugin/commit/439853d2717632c8697367808efec9575ac31a5e
here is waht I did so far

**Comment by mdarefin** [comment]
https://github.com/mdarefin/Convert-For-Each-Loop-to-Lambda-Expression-Eclipse-Plugin/commit/a7158007772e37f1cff4f5aa4182f1f3d41c222e
;etest push

**Comment by khatchad** [comment]
Please do not work on this issue yet. Please concentrate on the preconditions.

**Comment by khatchad** [comment]
Please revert your changes.

**Comment by khatchad** [comment]
After some thought, I think this is a non-issue. Embedded for loops should be perfectly fine.

**Comment by mdarefin** [comment]
:+1:
