### ISSUE TITLE
target directories in git

### ISSUE THREAD

**Issue by khatchad** [mdarefin/Convert-For-Each-Loop-to-Lambda-Expression-Eclipse-Plugin#16]
We should not have any target directories in git as that is for .class files (which we shouldn't be committing).

**Comment by mdarefin** [comment]
I remove the directory

**Comment by khatchad** [comment]
What is the commit number?

**Comment by khatchad** [comment]
I still see it https://github.com/mdarefin/Convert-For-Each-Loop-to-Lambda-Expression-Eclipse-Plugin/tree/master/edu.cuny.citytech.foreachlooptolambda.ui/target.

**Comment by khatchad** [comment]
Whiv commit fixed this?

**Comment by mdarefin** [comment]
in source Tree I am unable to delete the folder, I went to command line, so I have two target directory, one under edu.cuny.citytech.foreachlooptolambda.ui and one under edu.cuny.citytech.foreachlooptolambda.tests. should I remove both using git rm from command, or this files are important. I am not sure why the ui target is visible in the GitHub and the other one is not. any instruction would be helpful

**Comment by khatchad** [comment]
Nope, they are not important in terms of versioning. They simply hold the byte code files (.class) outputted from javac. They should not be in the versioning system. 

You should be able to delete them from SourceTree but you can also use the command line:

```
git rm -r target
```

`-r` means _recursive_. See http://git-scm.com/docs/git-rm.

**Comment by mdarefin** [comment]
Thank you

**Comment by khatchad** [comment]
It's still there: https://github.com/mdarefin/Convert-For-Each-Loop-to-Lambda-Expression-Eclipse-Plugin/tree/c5b40e9dc9fab06da9dc384d8fe1954f9847f089/edu.cuny.citytech.foreachlooptolambda.ui/target.

**Comment by mdarefin** [comment]
not sure how it's back I removed it https://github.com/mdarefin/Convert-For-Each-Loop-to-Lambda-Expression-Eclipse-Plugin/commit/6548943b8f64e4580844dac64fb3d5c75c09905a

**Comment by khatchad** [comment]
Nope, in https://github.com/mdarefin/Convert-For-Each-Loop-to-Lambda-Expression-Eclipse-Plugin/commit/6548943b8f64e4580844dac64fb3d5c75c09905a, you simply removed the contents of the file.

**Comment by mdarefin** [comment]
thanks for letting me know, I will again.  I used the command git rm -r target as suggested, will try sourceTree then

**Comment by khatchad** [comment]
`git rm -r target` should work. Are you sure you are in the directory that contains `target` when you issue that command?

**Comment by mdarefin** [comment]
yes, but every time I run the program it generate the folder, by default, there also a target directory under tests as well, but that one is not in GitHub,

**Comment by khatchad** [comment]
You can just add `target` to your `.gitignore`.

**Comment by mdarefin** [comment]
ok, there is no target directory in the UI, it's being removed
https://github.com/mdarefin/Convert-For-Each-Loop-to-Lambda-Expression-Eclipse-Plugin/tree/master/edu.cuny.citytech.foreachlooptolambda.ui

**Comment by khatchad** [comment]
:+1:
