### ISSUE TITLE
checkEnhancedForStatement() should collect warnings rather than returning them

### ISSUE THREAD

**Issue by khatchad** [mdarefin/Convert-For-Each-Loop-to-Lambda-Expression-Eclipse-Plugin#20]
Please do not work on this now. It is low priority. I noticed that we made a mistake in [ForeachLoopToLambdaRefactoring.checkEnhancedForStatement()](https://github.com/mdarefin/Convert-For-Each-Loop-to-Lambda-Expression-Eclipse-Plugin/blob/master/edu.cuny.citytech.foreachlooptolambda.ui/src/edu/cuny/citytech/foreachlooptolambda/ui/refactorings/ForeachLoopToLambdaRefactoring.java#L123). Instead of returning each time we find a problem, we should:
1. Create a status variable at the beginning of the method that will later be returned.
2. Add to (or merge) a new status each time we find a problem.
3. Return the final status at the end.

This way, if there are multiple problems with a loop, the developer will know all of them at once.

**Comment by mdarefin** [comment]
good idea,

**Comment by mdarefin** [comment]
got stuck on issue #10 so did little work on this one 
https://github.com/mdarefin/Convert-For-Each-Loop-to-Lambda-Expression-Eclipse-Plugin/commit/bd7bfe2f4a75534bc14984b0c6ef58642c1cc28b

**Comment by khatchad** [comment]
Please work on #8.
