### ISSUE TITLE
Small bug with `contains()`.

### ISSUE THREAD

**Issue by khatchad** [mdarefin/Convert-For-Each-Loop-to-Lambda-Expression-Eclipse-Plugin#21]
You have a small bug with #8. I could create a class named `raffi.java.util.Collection`, which would incorrectly pass your precondition.

**Comment by mdarefin** [comment]
In that case, if I use substring, that would have the same issue,

**Comment by khatchad** [comment]
Right. So those two methods are out.

**Comment by mdarefin** [comment]
How about .equal() when we get the name we keep the name upto the class or iterate name, and avoid <> declaration type. It will look for exact match

**Comment by mdarefin** [comment]
Can you check the code, it should fix the bug. 
https://github.com/mdarefin/Convert-For-Each-Loop-to-Lambda-Expression-Eclipse-Plugin/commit/43b945a957c93049d49c6dfc025f4d6a938d0ce6

**Comment by khatchad** [comment]
Did you test it?

**Comment by mdarefin** [comment]
I tested, it solve the problem  of contains, if I'm not mistaken, each class name like "java.util.Collection" are unique, in contain the promlem we had, it would true raffi.java.util.Collections, so I use .equals method, which has to be exact, so I get the class name and check with exact name in the set. Now I think I need to check in the rear case if a class implement itarable how to avoid those.

**Comment by khatchad** [comment]
What was your test case?

**Comment by mdarefin** [comment]
I did couple of them, 
https://gist.github.com/mdarefin/515be3899ed9bc110b22

**Comment by khatchad** [comment]
How about Collection<Integer>?

**Comment by mdarefin** [comment]
I did the Collection as well
https://gist.github.com/mdarefin/cc3c6602b8b92f7b4bc7

**Comment by mdarefin** [comment]
looks like it's working, but need to do more test,

**Comment by khatchad** [comment]
Hm, don't see any `Collection`s in https://gist.github.com/mdarefin/cc3c6602b8b92f7b4bc7. Can you try `Collection<Integer>`?

**Comment by mdarefin** [comment]
I try with the Collection<Integer> looks like the precondition is working upto this point

**Comment by mdarefin** [comment]
for checkCollection() it pass and for checkArray() it catch the exception

**Comment by mdarefin** [comment]
updated testCase, looks like working properly
https://gist.github.com/mdarefin/cc3c6602b8b92f7b4bc7

**Comment by khatchad** [comment]
I don't by it. I think it's worth at this point stopping at working on #1.

**Comment by mdarefin** [comment]
so how could I fix the contains() bug, beside following the instruction that you have to get the IType at issue #8

**Comment by khatchad** [comment]
Are you convinced that `equals()` doesn't work?

**Comment by khatchad** [comment]
Which commit fixed this bug?

**Comment by mdarefin** [comment]
here is the commit, I am adding the testCases, looks like it's wokring.  https://github.com/mdarefin/Convert-For-Each-Loop-to-Lambda-Expression-Eclipse-Plugin/commit/56a1c2354919ec967e7777cd62191cf98c797f75

**Comment by khatchad** [comment]
I believe that [this](https://github.com/mdarefin/Convert-For-Each-Loop-to-Lambda-Expression-Eclipse-Plugin/tree/master/edu.cuny.citytech.foreachlooptolambda.ui.tests/resources/ForeachLoopToLambda/testLoopIterateOverCollection) is the correct test case for this issue. According to [travis](https://travis-ci.org/mdarefin/Convert-For-Each-Loop-to-Lambda-Expression-Eclipse-Plugin), it's failing:

```
testLoopIterateOverCollection(edu.cuny.citytech.foreachlooptolambda.tests.ForeachLoopToLambdaRefactoringTest)  Time elapsed: 0.031 sec  <<< FAILURE!
```

```
Failed tests: 
  ForeachLoopToLambdaRefactoringTest.testLoopIterateOverCollection:83->RefactoringTest.helperFail:132->RefactoringTest.helperFail:92->RefactoringTest.assertFailedPrecondition:45->RefactoringTest.assertFailedPrecondition:33 Precondition was supposed to fail.
```

Why was the precondition supposed to fail [here](https://github.com/mdarefin/Convert-For-Each-Loop-to-Lambda-Expression-Eclipse-Plugin/blob/master/edu.cuny.citytech.foreachlooptolambda.ui.tests/resources/ForeachLoopToLambda/testLoopIterateOverCollection/in/A.java)? I think this is supposed to be a passing test case, no?

**Comment by khatchad** [comment]
Reopening due to failing test.

**Comment by mdarefin** [comment]
sure

**Comment by khatchad** [comment]
:+1:

**Comment by khatchad** [comment]
Actually, `startsWith()` isn't going to work either because I can create a type `java.util.Collection.raffi`, which does not contain the `stream()` method but passes your check. As such, you'll need to use `equals()` but you may need to do some maneuvering prior to that (like either removing the generics or using a different method to get the type name that doesn't include the type parameter).

**Comment by mdarefin** [comment]
:+1: got it, thanks, I will work on it,

**Comment by mdarefin** [comment]
the approach, I am working on is to getQualifiedName() which will provide us with the type like java.util.Colleciton(Integer) , and then I am using the split method to separate the name which would give the value of java.util.Collection only then we could compare, with equals("java.util.Collection") which should resolve the issue,

**Comment by khatchad** [comment]
There are some problems with the test case https://github.com/mdarefin/Convert-For-Each-Loop-to-Lambda-Expression-Eclipse-Plugin/commit/4d39c040b70b956a9a63ba103b28b0454340e028 and the fix https://github.com/mdarefin/Convert-For-Each-Loop-to-Lambda-Expression-Eclipse-Plugin/commit/415c40fc39b5fc3c4e35d89d5a163a085e8a8a33.

**Comment by khatchad** [comment]
Do you have a test for this fix?

**Comment by mdarefin** [comment]
I did create a testCase with type java.util.collection.forLoop and it's failing. and you can not use  java.util.Collection, it conflicts, could you also gist the testCase you did on it, so i could check it with your testCase as well

**Comment by khatchad** [comment]
Hm, I'm seeing this in travis:

```
testLoopIterateOverCollectionNamePack(edu.cuny.citytech.foreachlooptolambda.tests.ForeachLoopToLambdaRefactoringTest)  Time elapsed: 0.054 sec  <<< ERROR!
java.lang.IllegalArgumentException: A has structural errors.
    at edu.cuny.citytech.refactoring.common.tests.RefactoringTest.createCUfromTestFile(RefactoringTest.java:83)
    at edu.cuny.citytech.refactoring.common.tests.RefactoringTest.helperFail(RefactoringTest.java:90)
    at edu.cuny.citytech.refactoring.common.tests.RefactoringTest.helperFail(RefactoringTest.java:145)
    at edu.cuny.citytech.foreachlooptolambda.tests.ForeachLoopToLambdaRefactoringTest.testLoopIterateOverCollectionNamePack(ForeachLoopToLambdaRefactoringTest.java:119)
```

**Comment by khatchad** [comment]
Looks like this failure is coming up at the end of the log as well:

```
Tests run: 22, Failures: 3, Errors: 1, Skipped: 0
```

The three failures are from your exception tests, which is expected, but the error doesn't seem expected. More info:

```
Failed tests: 
  ForeachLoopToLambdaRefactoringTest.testLoopException:131->RefactoringTest.helperFail:145->RefactoringTest.helperFail:105->RefactoringTest.assertFailedPrecondition:45->RefactoringTest.assertFailedPrecondition:33 Precondition was supposed to fail.
  ForeachLoopToLambdaRefactoringTest.testLoopCatchException:135->RefactoringTest.helperFail:145->RefactoringTest.helperFail:105->RefactoringTest.assertFailedPrecondition:45->RefactoringTest.assertFailedPrecondition:33 Precondition was supposed to fail.
  ForeachLoopToLambdaRefactoringTest.testLoopThrowMultipleExceptions:143->RefactoringTest.helperFail:145->RefactoringTest.helperFail:105->RefactoringTest.assertFailedPrecondition:45->RefactoringTest.assertFailedPrecondition:33 Precondition was supposed to fail.
Tests in error: 
  ForeachLoopToLambdaRefactoringTest.testLoopIterateOverCollectionNamePack:119->RefactoringTest.helperFail:145->RefactoringTest.helperFail:90->RefactoringTest.createCUfromTestFile:83 » IllegalArgument
```

**Comment by khatchad** [comment]
My guess is that the code in `testLoopIterateOverCollectionNamePack` doesn't compile.

**Comment by khatchad** [comment]
Please get into the habit of testing your test cases in their own Java projects so that you know they're kosher.

**Comment by khatchad** [comment]
It's a bit of a pain but worth the effort.

**Comment by mdarefin** [comment]
:+1:  I have notie it's the test case class, accoding to our test case package name has to be p and class name A, which I am fixing now

**Comment by khatchad** [comment]
Do you still have the error in Travis?

**Comment by mdarefin** [comment]
no, I have fixed the test case

**Comment by khatchad** [comment]
I meant this one:

```
Tests in error: 
  ForeachLoopToLambdaRefactoringTest.testLoopIterateOverCollectionNamePack:119->RefactoringTest.helperFail:145->RefactoringTest.helperFail:90->RefactoringTest.createCUfromTestFile:83 » IllegalArgument
```

**Comment by mdarefin** [comment]
I was chceking the testCase testLoopIterateOverCollectionNamePack  and also debug it. looks like it's working properly.  I am checking for travis error, can you check now, and let me know if it still giving the error 

```
Tests run: 22, Failures: 3, Errors: 0, Skipped: 0, Time elapsed: 5.265 sec <<< FAILURE! - in edu.cuny.citytech.foreachlooptolambda.tests.ForeachLoopToLambdaRefactoringTest
```

3 exceptions testCase are failing

**Comment by mdarefin** [comment]
Below this are the fail test case 

```
Failed tests: 
  ForeachLoopToLambdaRefactoringTest.testLoopException:131->RefactoringTest.helperFail:145->RefactoringTest.helperFail:105->RefactoringTest.assertFailedPrecondition:45->RefactoringTest.assertFailedPrecondition:33 Precondition was supposed to fail.
  ForeachLoopToLambdaRefactoringTest.testLoopCatchException:135->RefactoringTest.helperFail:145->RefactoringTest.helperFail:105->RefactoringTest.assertFailedPrecondition:45->RefactoringTest.assertFailedPrecondition:33 Precondition was supposed to fail.
  ForeachLoopToLambdaRefactoringTest.testLoopThrowMultipleExceptions:143->RefactoringTest.helperFail:145->RefactoringTest.helperFail:105->RefactoringTest.assertFailedPrecondition:45->RefactoringTest.assertFailedPrecondition:33 Precondition was supposed to fail.
```

**Comment by khatchad** [comment]
Ah ok good. So the compile-time error is gone. But, could you add (maybe not now but later because you are busy with #9) some test cases that test different packages? For example, see https://gist.github.com/khatchad/ef07f7af98fbf18e1373.

**Comment by mdarefin** [comment]
:+1:  sounds good
