### ISSUE TITLE
Add a test case of Collection arrays

### ISSUE THREAD

**Issue by khatchad** [mdarefin/Convert-For-Each-Loop-to-Lambda-Expression-Eclipse-Plugin#26]
Please add the following test case for #8. This case should fail the preconditions:

``` java
java.util.Collection[] colArray = null;
for (Collection col : colArray)
    ;
```

**Comment by mdarefin** [comment]
This is suppose to fail, due to array, 
https://github.com/mdarefin/Convert-For-Each-Loop-to-Lambda-Expression-Eclipse-Plugin/commit/5658ab8a3aa26abc25ba744711543e5ab1742e06

**Comment by khatchad** [comment]
:+1:
