### ISSUE TITLE
Add a test case for classes that directly implement java.util.Collection

### ISSUE THREAD

**Issue by khatchad** [mdarefin/Convert-For-Each-Loop-to-Lambda-Expression-Eclipse-Plugin#27]
For #8, please add a case for classes that **directly** implement `java.util.Collection`. This is because I am not sure if the supertype hierarchy will give you information about the type from which it was created. Here's an example:

``` java
class C implements java.util.Collection {
    //...
}
class A {
    void m() {
        C c = null;
        for (Object obj : c)
            ;
    }
}
```

This case should pass the preconditions because `C` **directly** implements `java.util.Collection`.

**Comment by mdarefin** [comment]
:+1:  got it

**Comment by mdarefin** [comment]
testCase added
https://github.com/mdarefin/Convert-For-Each-Loop-to-Lambda-Expression-Eclipse-Plugin/tree/master/edu.cuny.citytech.foreachlooptolambda.ui.tests/resources/ForeachLoopToLambda/testLoopIterateOverCollectionImplement

**Comment by khatchad** [comment]
:+1:
