### ISSUE TITLE
Missing test case for #8

### ISSUE THREAD

**Issue by khatchad** [mdarefin/Convert-For-Each-Loop-to-Lambda-Expression-Eclipse-Plugin#28]
For #8, you have a test method [`testLoopImplementlIterable()`](https://github.com/mdarefin/Convert-For-Each-Loop-to-Lambda-Expression-Eclipse-Plugin/blob/master/edu.cuny.citytech.foreachlooptolambda.ui.tests/test%20cases/edu/cuny/citytech/foreachlooptolambda/tests/ForeachLoopToLambdaRefactoringTest.java#L102-L104) but no corresponding test resouce in [ForeachLoopToLambda](https://github.com/mdarefin/Convert-For-Each-Loop-to-Lambda-Expression-Eclipse-Plugin/tree/master/edu.cuny.citytech.foreachlooptolambda.ui.tests/resources/ForeachLoopToLambda).

**Comment by mdarefin** [comment]
here is the test case
https://github.com/mdarefin/Convert-For-Each-Loop-to-Lambda-Expression-Eclipse-Plugin/tree/master/edu.cuny.citytech.foreachlooptolambda.ui.tests/resources/ForeachLoopToLambda/testLoopImplementlIterable/in

**Comment by khatchad** [comment]
Please list the commit that fixes this issue. Thanks.

**Comment by mdarefin** [comment]
:+1:  here is the commit 
https://github.com/mdarefin/Convert-For-Each-Loop-to-Lambda-Expression-Eclipse-Plugin/commit/1044e78ebfb8d44f447c5167225d4c38a8acb382

**Comment by khatchad** [comment]
`Iterable`.

**Comment by khatchad** [comment]
Sorry, it looks correct.
