### ISSUE TITLE
Misnamed directories

### ISSUE THREAD

**Issue by khatchad** [mdarefin/Convert-For-Each-Loop-to-Lambda-Expression-Eclipse-Plugin#3]
Looks like there's still some misnamed directories laying around, e.g., edu.cuny.citytech.defaultrefactoring.tests.

**Comment by khatchad** [comment]
Ah, these directories still have the `pom.xml` files in them. Those files need to be moved to the new directories.

**Comment by mdarefin** [comment]
Last time when we import some new test-case from your repository, it renamed. I have noticed the issue, but wasn't sure what to do.

**Comment by khatchad** [comment]
No problem.

**Comment by khatchad** [comment]
You can move the `pom.xml` files in the correct directories and delete these.

**Comment by khatchad** [comment]
More work to do here.

**Comment by khatchad** [comment]
Are we cool on this one?

**Comment by mdarefin** [comment]
I am trying to modify the visitor pattern. deleting the unnecessary, could you check the xml file, if that's implement properly.

**Comment by khatchad** [comment]
Misnamed directories shouldn't have anything to do with the visitor pattern, no? Looks like you may have fixed this issue in https://github.com/mdarefin/Convert-For-Each-Loop-to-Lambda-Expression-Eclipse-Plugin/commit/f2cb9ce8e9ac2d202df52f2d43652738298a8b00. Can you confirm? If so, please close.

**Comment by khatchad** [comment]
Also, I commented on the XML file in https://github.com/mdarefin/Convert-For-Each-Loop-to-Lambda-Expression-Eclipse-Plugin/commit/b0e337155b4fd65b116fcce7dd48cc1b85576a3e.
