### ISSUE TITLE
Print input ASTs

### ISSUE THREAD

**Issue by khatchad** [mdarefin/Convert-For-Each-Loop-to-Lambda-Expression-Eclipse-Plugin#5]
You receive an IMethod. Get the AST from the IMethod. Remember that the AST is for the entire compilation unit. That means it represents the entire .java file. You can get an AST from a compilation unit. Create a visitor that visits all enhanced for loops in the AST.

**Comment by khatchad** [comment]
How's it going?

**Comment by mdarefin** [comment]
I am working on it, no significant cahnge, just change the name and edit
xml file add lambda refactoring option

**Comment by khatchad** [comment]
OK cool. Once you fix the renaming, make sure the commit and push. That way, we have a nice revision history,

**Comment by mdarefin** [comment]
I push on git hub, you may take a look, to see if the XML files is okay,
also what would be in the commandID

**Comment by khatchad** [comment]
Thanks, I will. Also, could you make me a collaborator on this project?

**Comment by khatchad** [comment]
Also, did you have any questions about this task?

**Comment by mdarefin** [comment]
Sure I will do so, I actually do have questions. I send you them later on.

**Comment by mdarefin** [comment]
I create LambdaConversionVisitor it extends ASTVisitor I have method visitNode(ASTNode node) and visit(EnhancedForStatement node) so, both of them are boolean types, how could I implement this to the iMethod. could you take a look at the parse method I created to get the AST from CompilationUnit

**Comment by khatchad** [comment]
You should only override the [`visit(EnhancedForStatement node)`](http://help.eclipse.org/mars/index.jsp?topic=/org.eclipse.jdt.doc.isv/reference/api/org/eclipse/jdt/core/dom/ASTVisitor.html&anchor=visit-org.eclipse.jdt.core.dom.EnhancedForStatement-) method (I think).

**Comment by khatchad** [comment]
Which parsing code?

**Comment by khatchad** [comment]
You'll need to pass an instance of your visitor to [`accept(ASTVisitor visitor)`](http://help.eclipse.org/mars/index.jsp?topic=/org.eclipse.jdt.doc.isv/reference/api/org/eclipse/jdt/core/dom/ASTVisitor.html&anchor=visit-org.eclipse.jdt.core.dom.EnhancedForStatement-).

**Comment by mdarefin** [comment]
Parsing is a method, as you instructed to get the ICompilationUnit and get all the AST node from it

**Comment by khatchad** [comment]
So, you'll need an instance of an `ASTNode` that will accept your `ASTVisitor`.

**Comment by mdarefin** [comment]
yeah, that's what I was thinking

**Comment by mdarefin** [comment]
<img width="894" alt="screen shot 2015-07-14 at 12 26 50 pm" src="https://cloud.githubusercontent.com/assets/9343226/8678849/f7d53e1e-2a24-11e5-98ac-c971e35dd995.png">
getting this error, is it for the xml files.

**Comment by khatchad** [comment]
Are you talking about [this](https://github.com/mdarefin/Convert-For-Each-Loop-to-Lambda-Expression-Eclipse-Plugin/blob/master/edu.cuny.citytech.foreachlooptolambda.ui/src/edu/cuny/citytech/foreachlooptolambda/ui/refactorings/ForeachLoopToLambdaRefactoring.java#L72-L78) method?

**Comment by mdarefin** [comment]
yes,

**Comment by mdarefin** [comment]
I am not seeing any out put, keep getting the above error, so not sure it was properly implemented or not

**Comment by khatchad** [comment]
I will comment on https://github.com/mdarefin/Convert-For-Each-Loop-to-Lambda-Expression-Eclipse-Plugin/commit/0554934a884f4d3b6c571421b9bdfb41d2bf575b.

**Comment by khatchad** [comment]
Actually https://github.com/mdarefin/Convert-For-Each-Loop-to-Lambda-Expression-Eclipse-Plugin/commit/9240153d64a2a6725b7a8c99a2947877266a8e5a.

**Comment by khatchad** [comment]
Please see my inline code comments .

**Comment by khatchad** [comment]
Yes, you should revert these changes in the XML file as they are not relevant for #5.

**Comment by mdarefin** [comment]
For issue #5, I see you have created a lamdaVisit and have compilationUnit accepting it, what is there are more than one visit method in the LambdaConversionVisitor class and without override or getting proper EnhancedForStatement node, how to make sure it visit the for-each method.

**Comment by khatchad** [comment]
> what is there are more than one visit method in the LambdaConversionVisitor class 

Do you mean what happens if you _override_ more than one method in the `LambdaConversionVisitor` class?

**Comment by khatchad** [comment]
> and without override or getting proper EnhancedForStatement node, how to make sure it visit the for-each method.

Do you mean "without overriding the `visit(EnhancedForStatement node)`, how do you ensure that the visitor visits enhanced for statement nodes?"

**Comment by mdarefin** [comment]
yes

**Comment by khatchad** [comment]
Yes to which one?

**Comment by mdarefin** [comment]
without overriding the visit(EnhancedForStatement node), how do you ensure that the visitor visits enhanced for statement nodes?" if we have more than one visit method in the Visitor class.

**Comment by mdarefin** [comment]
and the node we are getting from Compilation Unit, which has other nodes besides the EnhancedForStatement, how could we ensure, would it pass all the other node as well, and check if there is any other EnhancedForStatement instance, if not stay false, otherwise true.

**Comment by khatchad** [comment]
> "without overriding the `visit(EnhancedForStatement node)`, how do you ensure that the visitor visits enhanced for statement nodes?"

The visitor will visit each node of the AST no matter how many methods you override. This is because your visitor extends `ASTVisitor`. `ASTVisitor` is like the default implementation, which basically just visits the nodes and no more. When you extend `ASTVisitor` and override its methods, that's where you can add additional functionality, like printing nodes, for example. You must be sure, though, to call the super implementation of the method you are overriding. Otherwise, you'll most likely stop the visitation.

**Comment by mdarefin** [comment]
now, let's see inside the for-loop we are checking if there is any EnhancedForStatement node, if there is, it will return true, now if I want to print the node inside public RefactoringStatus checkFinalConditions, how could I do so, because this method is already Override RefactoringStatus.

**Comment by khatchad** [comment]
> and the node we are getting from Compilation Unit, which has other nodes besides the EnhancedForStatement,

It is the **root** of other such nodes.

> how could we ensure, would it pass all the other node as well,

It doesn't pass them. It visits **all** of the nodes. Remember, you are _extended_ `ASTVisitor` and only overriding a single method. That doesn't mean the other methods in `ASTVisitor` disappear. As long as you return the return value from the super implementation, the visitation will continue.

> and check if there is any other EnhancedForStatement instance, if not stay false, otherwise true.

This is part of the visitor pattern. It will execute each of the corresponding methods for each node visited.

I hope I am understanding these questions correctly!

**Comment by khatchad** [comment]
> now, let's see inside the for-loop we are checking if there is any EnhancedForStatement node,

Do you mean in the visitor? If so, we are not checking anything. That method is only called when the visitor visits that kind of node. There's nothing to check.

> if there is, it will return true,

In the visitor? Returning `true` makes the visitation continue, but you shouldn't worry about that. You should simply return the value returned by a call to the super implementation.

> now if I want to print the node inside public RefactoringStatus checkFinalConditions,

The printing should not happen here. It should be done in the visitor.

**Comment by mdarefin** [comment]
got it, Thanks. Now for the status instance of RefactoringStatus, what should we return there, or just leave it like that. what else need to be done inside the for-loop.

**Comment by khatchad** [comment]
> got it, Thanks. Now for the status instance of RefactoringStatus, what should we return there, or just leave it like that. what else need to be done inside the for-loop.

Nothing.

**Comment by mdarefin** [comment]
Thanks, ok, I will then start working at #6

**Comment by khatchad** [comment]
You are not done with #5.

**Comment by khatchad** [comment]
You need to review, accept, and merge https://github.com/mdarefin/Convert-For-Each-Loop-to-Lambda-Expression-Eclipse-Plugin/pull/7. Then, you still need to print each enhanced for loop node. The printing code will go in the visitor.

**Comment by mdarefin** [comment]
I am unable to merge from the Github, I have to go through command line. how could I check and merge from commad line

**Comment by khatchad** [comment]
### Checkout via command line

If you cannot merge a pull request automatically here, you have the option of checking it out via command line to resolve conflicts and perform a manual merge.

https://github.com/khatchad/Convert-For-Each-Loop-to-Lambda-Expression-Eclipse-Plugin.git

**Step 1:** From your project repository, check out a new branch and test the changes.

```
git checkout -b khatchad-master master
git pull https://github.com/khatchad/Convert-For-Each-Loop-to-Lambda-Expression-Eclipse-Plugin.git master
```

**Step 2:** Merge the changes and update on GitHub.

```
git checkout master
git merge --no-ff khatchad-master
git push origin master
```

**Comment by mdarefin** [comment]
<img width="754" alt="screen shot 2015-07-14 at 11 44 11 pm" src="https://cloud.githubusercontent.com/assets/9343226/8690458/805d5688-2a82-11e5-9d5d-62dd988c968d.png">
got this error, Permission to khatchad/Java-8-Interface-Refactoring.git denied to mdarefin.

**Comment by khatchad** [comment]
Can you post the plain text of the errors (instead of a screenshot)?

**Comment by mdarefin** [comment]
mds-MacBook-Pro:Java-8-Interface-Refactoring WaLiD$ git push origin master
remote: Permission to khatchad/Java-8-Interface-Refactoring.git denied to mdarefin.
fatal: unable to access 'https://github.com/khatchad/Java-8-Interface-Refactoring.git/': The requested URL returned error: 403

**Comment by khatchad** [comment]
Can you post the entire plain text like you have in the screenshot?

**Comment by khatchad** [comment]
We can screen share if you give me a code from http://chrome.google.com/remotedesktop

**Comment by mdarefin** [comment]
sure, let me know when you would be available

**Comment by mdarefin** [comment]
Access code is 110013245539

**Comment by mdarefin** [comment]
here is the error: 
mds-MacBook-Pro:Java-8-Interface-Refactoring WaLiD$ git push origin master
remote: Permission to khatchad/Java-8-Interface-Refactoring.git denied to mdarefin.
fatal: unable to access 'https://github.com/khatchad/Java-8-Interface-Refactoring.git/': The requested URL returned error: 403

**Comment by khatchad** [comment]
Can you post the entire plain text like you have in the screenshot?

**Comment by mdarefin** [comment]
Hi mdarefin/Convert-For-Each-Loop-to-Lambda-Expression-Eclipse-Plugin!

Your friend Shahrear has invited you to:

Flags Don't Matter
Black Bear Brooklyn - Brooklyn, NY

Tickets & More: http://www.bandsintown.com/event/10543791?artist=Flags%20Don%27t%20Matter&sender_id=6989416&came_from=197&utm_source=event_invitation&utm_medium=email_more&utm_campaign=Event%20Invitation

Seeya there,

~ Bandsintown Inc. © 2015 | http://bnds.in/HdWafg
215 Lexington Avenue, 18th floor New York, NY 10016
To unsubscribe http://mail.bandsintown.com/mpss/u/6AA/oi4VAA/t.1qb/4jWLBwmBQBCWVPkuDHtdbw/ut18
