### ISSUE TITLE
Fix plug-in renaming

### ISSUE THREAD

**Issue by khatchad** [mdarefin/Convert-For-Each-Loop-to-Lambda-Expression-Eclipse-Plugin#6]
There's still a bunch of stuff that has the old plug-in name. Can you please complete the renaming? You can use the find-and-replace mechanism in Eclipse.

Here are some examples:
- https://github.com/mdarefin/Convert-For-Each-Loop-to-Lambda-Expression-Eclipse-Plugin/blob/master/edu.cuny.citytech.foreachlooptolambda.ui/bundle.properties
- https://github.com/mdarefin/Convert-For-Each-Loop-to-Lambda-Expression-Eclipse-Plugin/blob/master/edu.cuny.citytech.foreachlooptolambda.ui/plugin.xml
- https://github.com/mdarefin/Convert-For-Each-Loop-to-Lambda-Expression-Eclipse-Plugin/blob/master/edu.cuny.citytech.foreachlooptolambda.ui.tests/META-INF/MANIFEST.MF
- https://github.com/mdarefin/Convert-For-Each-Loop-to-Lambda-Expression-Eclipse-Plugin/blob/master/edu.cuny.citytech.foreachlooptolambda.ui.tests/test%20cases/edu/cuny/citytech/foreachlooptolambda/tests/MigrateSkeletalImplementationToInterfaceRefactoringTest.java
  - The class should be renamed here.

**Comment by mdarefin** [comment]
I am not sure what to modify at MANIFEST.MF file

**Comment by khatchad** [comment]
@mdarefin `Bundle-Name: Default Refactoring Tests`.

**Comment by mdarefin** [comment]
@khatchad  Bundle-Name: would it be the name I put in the bundle "Eclipse Advance ForLoop to Lambda Refactoring Plugin" or jut put Default Refactoring Tests

**Comment by mdarefin** [comment]
@khatchad the test fails when I refactor the class name in test class from Migrate Skelaton to ForEach

**Comment by khatchad** [comment]
What is the error you are receiving? But, I wouldn’t work on this issue today since #5 is the one is due today. Once you finish #5, you can work on this one.
