### ISSUE TITLE
Precondition Iterate over Java Collection Class

### ISSUE THREAD

**Issue by mdarefin** [mdarefin/Convert-For-Each-Loop-to-Lambda-Expression-Eclipse-Plugin#8]
The enhanced for loop should be iterating over an instance of java.util.Collection, rather than an array, in order to be able to obtain a stream.

**Comment by khatchad** [comment]
It might be helpful to have a look at: ![NetBeans source](https://openlab.citytech.cuny.edu/?get_group_doc=16323/1435267147-isSafeToRefactor.png), in particular, the `iteratesOverIterable()` method.

**Comment by khatchad** [comment]
But, even if you don't look at the NetBeans code for a comparison, intuitively, you'll need to check parts of the enhanced for loop node, as you pointed out yesterday. Have a look at the grammar (https://en.wikipedia.org/wiki/Formal_grammar) from http://help.eclipse.org/mars/index.jsp?topic=%2Forg.eclipse.jdt.doc.isv%2Freference%2Fapi%2Forg%2Feclipse%2Fjdt%2Fcore%2Fdom%2FEnhancedForStatement.html:

``` java
 for ( FormalParameter : Expression )
                        Statement
```

Looks like you'll be particularly interested in Expression. You can get it by using the getExpression() (http://help.eclipse.org/mars/topic/org.eclipse.jdt.doc.isv/reference/api/org/eclipse/jdt/core/dom/EnhancedForStatement.html#getExpression--) method.

**Comment by khatchad** [comment]
This one might be a little tough. You may need to resolve bindings when you build the AST. What does is gives you a bridge from the "AST world" to the "Java model world," meaning that from AST nodes you can retrieve IJavaElements. Using the ASTView view in Eclipse should be very helpful for you here. There, you can see which IJavaElements are bound to particular ASTNodes. Hope that helps!

**Comment by khatchad** [comment]
By the way, "instance of `java.util.Collection`" means an instance of `java.util.Collection` or any **subtypes** of `java.util.Collection`. Fortunately, there is a plethora of helper methods in the JDT to obtain subtype hierarchies.

**Comment by mdarefin** [comment]
is it possible to check with
 public void endVisit(ArrayType node) {
        this.isInstanceOfCollection = true; 
    }

**Comment by mdarefin** [comment]
what if there is an Array declear inside of the EnhancedForloop. In my understanding that would loop wouldn't be able to convert into lambdaExpression. should we check with ArrayType node.

**Comment by khatchad** [comment]
The problem states that the loop must iterate over a collection. You can iterate over other things other than arrays that are also not collections. As such, simply checking for an array would be incorrect.

**Comment by khatchad** [comment]
Again, you don't need a visitor to solve this problem.

**Comment by mdarefin** [comment]
I try to solve the issue with expression and check if it's an instance of collections. When I check the expression, example:
int [] number = {2,2,3,4}
for(Integer i : number){
     System.out.println();
}
it give me the expression value is number. but I did print out  get class, which shows it's under ASTNode class. So if i am checking if it's a part of collection giving me false every item. is there any way to check when declare a variable like number which is instance of array class, to check is it's part of collections or not.

**Comment by khatchad** [comment]
> I try to solve the issue with expression and check if it's an instance of collections.

That's not quite the correct approach. You don't want to check that the expression is an instance of a `java.util.Collection`. Remember, every expression in Java has a compile-type type (because it is a strongly typed language). You want to check that the type of the expression evaluates to `java.util.Collection` or any of its subtypes. ASTView would be helpful here. There, you can see the bindings of the expression.

**Comment by mdarefin** [comment]
is there any method in visitor to check that, like getType() or I saw netbeans have getType() method, i didn't see one for eclipse.

**Comment by khatchad** [comment]
Again, you don't need a visitor to solve this problem. This should be done in the refactoring class. A visitor is only good for visiting many nodes of a certain type. You already have the node you need.

**Comment by khatchad** [comment]
Hint: create a new method in the `ForeachLoopToLambdaRefactoring` class:

``` java
private static RefactoringStatus checkEnhancedForStatementIteratesOverCollection(EnhancedForStatement enhancedForStatement, IProgressMonitor pm)
```

Call this method from `checkEnhancedForStatement()`.

**Comment by khatchad** [comment]
In `checkEnhancedForStatementIteratesOverCollection()`, break apart the `enhancedForStatement` (get the expression, just like you had done in the visitor; you were on the right track!). Then, try to get the **type** that of that expression. Note that this is **different than** the Java type (the java type will be `ExpressionStatement` or something from the JDT). The JDT has its own way of representing types of expressions (which are called bindings).

**Comment by mdarefin** [comment]
thanks for the hint,

**Comment by mdarefin** [comment]
should I check for something like this 

ITypeBinding binding = enhancedForStatement.getType(); how to get biding or collection or check this with collection

**Comment by mdarefin** [comment]
or should use enhancedForStatement.isGenericType() instanceof Collections or getTypeArguments(). i need to understand IProgressMonitor better 

http://help.eclipse.org/juno/index.jsp?topic=%2Forg.eclipse.jdt.doc.isv%2Freference%2Fapi%2Forg%2Feclipse%2Fjdt%2Fcore%2Fdom%2FITypeBinding.html

**Comment by khatchad** [comment]
> should I check for something like this
> 
> ITypeBinding binding = enhancedForStatement.getType(); how to get biding or collection or check this with collection

Nope. Actually, you had it earlier with the `getExpression()`. You want the type of whatever that method returns. Remember, I said that every _expression_ in Java has a type, not every statement (I think that's what I said).

**Comment by khatchad** [comment]
> need to understand IProgressMonitor better

Don't worry about it now. You can always pass in `new NullProgressMonitor()` or even `null` sometimes.

**Comment by khatchad** [comment]
Or you can just pass the one you have.

**Comment by khatchad** [comment]
It's not a big deal right now.

**Comment by mdarefin** [comment]
ok, thank you

**Comment by khatchad** [comment]
Do you see the binding in the ASTView?

**Comment by khatchad** [comment]
I think it's in blue.

**Comment by mdarefin** [comment]
what if we create an array of string where we keep all the name related to collection like list, map, set. and then check through, if it match, let me know what do you think about this approach, I am thinking other possible approach as well

**Comment by mdarefin** [comment]
could you check the code if it's the right approach, or any suggestion to solve it in better way 
https://github.com/mdarefin/Convert-For-Each-Loop-to-Lambda-Expression-Eclipse-Plugin/commit/27b57794cc57abc096770d8fc78fbee87d37955e

**Comment by khatchad** [comment]
Nice try but I can give you an example where it doesn't work (counter example). I could create my own class and have it implement [Iterable](https://docs.oracle.com/javase/8/docs/api/java/lang/Iterable.html). Then, I can use an enhanced for loop to iterate over instances of that class.

**Comment by khatchad** [comment]
The precondition would pass in this case but my class wouldn't have a `stream()` method.

**Comment by mdarefin** [comment]
What if we take a different  approach like, we know lambda iterate over collections, and doesn't  iterate over array, in that case there are less class that it doesn't  iterate over we could check those. What else lambda doesn't iterate over beside array.

**Comment by khatchad** [comment]
> What else lambda doesn't iterate over beside array.

Do you mean what else can an enhanced for loop iterate over besides an array?

**Comment by mdarefin** [comment]
Enhanced  for loop can iterate  over array and collection, the question  lambda expression can not iterate over array, it's iterate over collections, so what else  the lambda expression  can't  iterate over like array.

**Comment by khatchad** [comment]
A lambda expression doesn't iterate over anything.

**Comment by mdarefin** [comment]
I was asking enhanced forLoop can iterate over array in general, during  lambda conversion if the loop iterate over array, we can't convert it. beside array what are the other class like array.

**Comment by khatchad** [comment]
> I was asking enhanced forLoop can iterate over array 

Yes, an enhanced for loop can iterate over an array and any type that implements the `java.util.Iterable` interface.

> during lambda conversion if the loop iterate over array, we can't convert it.

Yes, that's correct.

> beside array what are the other class like array.

Any type that implements the `java.util.Iterable` interface.

**Comment by mdarefin** [comment]
Thank you

**Comment by khatchad** [comment]
No problem. Is it now clear why you can't simply check if it's not an array? In fact, NetBeans also does not simply check that it's an array. This is because they want the stream() method, which is declared in `java.util.Collection` (and not in `java.util.Iterable`).

**Comment by khatchad** [comment]
Hi @mdarefin. Do you have any other questions, particularly about the methods I posted? Can you finish this one today?

**Comment by mdarefin** [comment]
Where did you post the methods, I didn't see any pull request or gist files. could you give me the link please.

**Comment by mdarefin** [comment]
as of the precondition we have I check with a class implements Iterable<Type> looks like the precondition being able to detect that doesn't iterate over collection, and also it's passes all the other test, now I need a test Case that fail the precondition, than I will be able to work on what need to be changes, here is my test case for iterate, 
https://gist.github.com/mdarefin/515be3899ed9bc110b22

**Comment by mdarefin** [comment]
As I am doing bunch of testCases, the issue I am faciing is eventough the method doesn't have any forEachLoop the plug-in is not showing any warning that this method doesn't have enhancedForLoop

**Comment by khatchad** [comment]
I posted the methods at https://github.com/mdarefin/Convert-For-Each-Loop-to-Lambda-Expression-Eclipse-Plugin/commit/76f281885cbbac64911883fef09b9d0bb3811113.

**Comment by khatchad** [comment]
This is a good start but not sufficient (as you know). So, we need to expand this. What you should do is check either if:
1. This type **is** `java.util.Collection` (which you have already started to do here, or
2. This type **implements** `java.util.Collection` (in the case that the type is a class), or
3. This type **extends** `java.util.Collection` (in the case that the type is an interface).

So, (1) you have just about done (I filled #21). For (2) and (3), I recommend using the following methods in the following order:
1. http://help.eclipse.org/mars/topic/org.eclipse.jdt.doc.isv/reference/api/org/eclipse/jdt/core/dom/IBinding.html#getJavaElement-- (which you can call on the `ITypeBinding` you have to get the corresponding `IJavaElement`, which should be an instance of `IType`),
2. http://help.eclipse.org/mars/topic/org.eclipse.jdt.doc.isv/reference/api/org/eclipse/jdt/core/IType.html#newSupertypeHierarchy-org.eclipse.core.runtime.IProgressMonitor- (to get the supertype hierarchy), and
3. Either:
   - http://help.eclipse.org/mars/topic/org.eclipse.jdt.doc.isv/reference/api/org/eclipse/jdt/core/ITypeHierarchy.html#getAllInterfaces-- or
   - http://help.eclipse.org/mars/topic/org.eclipse.jdt.doc.isv/reference/api/org/eclipse/jdt/core/ITypeHierarchy.html#getAllSuperInterfaces-org.eclipse.jdt.core.IType-

For this last one, I'm not quite sure. Try it out and see what it returns. You'll need some good test cases here. Three I can think of are:
1. Iterate over an instance of `java.util.Collection` (which you have).
2. Iterate over an instance of `java.util.List`.
3. Iterate over an instance of `java.util.ArrayList`.

All three of these should pass.

**Comment by mdarefin** [comment]
how could go from IElement to IType, how can I get the newSuperTypeHierarchy from JavaElement, I didn't find any method in JavaElement to get the IType

**Comment by mdarefin** [comment]
How could I get the iTypeHeirchay from IJavaElement, could not find any particular method

**Comment by khatchad** [comment]
> how could go from IElement to IType,

What is an IElement?

> how can I get the newSuperTypeHierarchy from JavaElement

From (2) above: http://help.eclipse.org/mars/topic/org.eclipse.jdt.doc.isv/reference/api/org/eclipse/jdt/core/IType.html#newSupertypeHierarchy-org.eclipse.core.runtime.IProgressMonitor- (to get the supertype hierarchy), 

> , I didn't find any method in JavaElement to get the IType

It's in `IType`, which is a subtype of `IJavaElement`. From (1) above, the `IJavaElement` you receive should be an instance of an `IType`. You'' need to downcast it.

**Comment by mdarefin** [comment]
well since IType sub-iterface of IElement, it should take the method from IElement, but when I am trying to get the ITypeHierarchyI from the IElement, it's keep giving me error, uless I cast (IType) nodeElementType and put into try-catch.
https://github.com/mdarefin/Convert-For-Each-Loop-to-Lambda-Expression-Eclipse-Plugin/commit/a2a84422a334e02fb68ebf4a5fa03bf28dda3409

**Comment by khatchad** [comment]
I'm not sure why you are dealing with `IElement`s. Please inform me of the following. From (1):

> http://help.eclipse.org/mars/topic/org.eclipse.jdt.doc.isv/reference/api/org/eclipse/jdt/core/dom/IBinding.html#getJavaElement-- (which you can call on the ITypeBinding you have to get the corresponding IJavaElement, which should be an instance of IType),

When you call [ITypeBinding.getJavaElement](http://help.eclipse.org/mars/topic/org.eclipse.jdt.doc.isv/reference/api/org/eclipse/jdt/core/dom/IBinding.html#getJavaElement--), what is the run time type that is returned? Since it is an `ITypeBinding`, I believe that the run time type should be `IType`. In fact, that is what the API documentation says. Please use a debugger to get the answer.

**Comment by mdarefin** [comment]
the IDE doesn't allow to get  "ITypeBinding.getJavaElement" without casting (ITypeBinding) and if you cast it gives an error, that you can't cast this class to Element, but if you store the return into IElementType than you don't need casting, so for Step one can you be liite more be spacific. should I store into IType variable which also require (IType) casting,

**Comment by mdarefin** [comment]
@khatchad Could you please look at the code https://github.com/mdarefin/Convert-For-Each-Loop-to-Lambda-Expression-Eclipse-Plugin/commit/aa3ce882107a7808faa8728be0a28d0a7607f652 and let me, is this following the instruction, if not I am need to understand the setps better

**Comment by khatchad** [comment]
I think you can slightly speed up `checkEnhancedForStatementIteratesOverCollection()`. Instead of using a boolean variable, just return `true` or `false`.

**Comment by mdarefin** [comment]
:+1:  got it
